### ISSUE TITLE
Right click handler not working properly

### ISSUE THREAD

**Issue by colek42** [pcbje/ggraph#1]
First thanks for open sourcing this!

Multi-select does not seem to be working correctly in Chrome Version 55.0.2883.87 m (64-bit)

 ![ Screen Recording ](http://g.recordit.co/iO1AaNPquH.gif)

**Comment by colek42** [comment]
Suggest Ctrl+Left click

**Comment by riadd** [comment]
Right click handler also not working properly in Firefox Developer Edition 52.0a2 (2016-12-31) (32-bit) (Windows 10)

**Comment by pcbje** [comment]
Thanks! I'm happy to hear people like it!

Are you not able to select nodes, or are the wrong nodes selected? Can you check the demo-page again and see if the problem is still there? (Note that right-click no longer is used for selection)

**Comment by riadd** [comment]
Thanks for the update. 

Regarding the previous bug: The proper nodes were selected. The issue was that after releasing the right mouse button, the selection mode was still enabled, resulting in accidently selecting and deselecting nodes while moving the mouse without any buttons pressed. That is what you're seeing in the gif posted above.

The new version seems to work better, but it's still possible to be stuck in selection mode without having any buttons pressed:
1) Left click
2) Drag mouse and select nodes
3) Release left click
4) Left click
5) Drag mouse
6) Release click

Again the cursor is stuck in selection mode, selecting areas while the mouse is moved now.

**Comment by pcbje** [comment]
Thanks for clarifying! It seems to be a problem caused by the browser actually selecting some HTML-elements during multi-select. I've now disabled text selection within the svg. Can you check the demo once more? Also make sure the latest version is loaded.

**Comment by riadd** [comment]
Works now. Thanks!
